spring:
  application:
    name: School Information System
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: abdul-razak
    password: 206207
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret-key: 22f1b537e800549a72e676117ff08c2dc02d980e3827b09eb79d5d25f53e6c45
