spring:
  application:
    name: Spring Security Demo Project
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2-database/spring-security-db
    username: abdul-razak
    password: 206207
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  security:
#    user:
#      name: admin
#      password: admin
